### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by zbllbz6** [modelscope/normal-depth-diffusion#2]
When will the rendered multi-view images of Objaverse-dataset and the rendering code be made public? Thank you

**Comment by lingtengqiu** [comment]
Our rendering code based on Unity. If you need it, we can provide it to you. We will be releasing the rendering data ASAP.

**Comment by lingtengqiu** [comment]
By the way, if you are not familiar with Unity's rendering, we can also assist you in rendering the data format you desire.

**Comment by zbllbz6** [comment]
Grateful for releasing rendering code. A Blender-based rendering would be even better if possible. I am looking forward to your data and work in future very much.
