### ISSUE TITLE
Image conditioned

### ISSUE THREAD

**Issue by fefespn** [modelscope/normal-depth-diffusion#9]
Hey, 
Thanks a lot for your work.
Is there a way to use the current arch and weights to condition the input for image ? so we can use it as normal/depth estimator ?

**Comment by lingtengqiu** [comment]
We did not attempt to predict the normal or depth of given rgb imgs. But I think it is  possible to use the existing framework, you just need to find a way to inject the contexture of the image into the diffusion Unet, (e.g., Zero123 concats VAE features with x_0 features.) 

Besides, [marigold](https://github.com/prs-eth/Marigold) inspires us to design a diffusion-based estimator for depth/normal. I suggest consulting this work for reference : ).

**Comment by fefespn** [comment]
Thanks a lot !
